### PR TITLE
topotato: WIP test_bgp_blackhole_community.py

### PR DESCRIPTION
**Pull request by Chromico**
All the other tests work except for bgp_no_advertise_ibgp.

### CODE REVIEW

**Comment by eznix86** [comment]
Can I take over this ?

**Comment by Chromico** [comment]
Sure, go for it.

**Comment by eznix86** [comment]
The issue could be a problem internal to topotato, in any case, no solution yet for this.

```
E       topotato.exceptions.TopotatoCLICompareFail: json["totalPrefixCounter"] dict value is different (
E       --- Expected value
E       +++ Current value
E       @@ -1 +1 @@
E       -2
E       +0)
E       expected key(s) ['10.255.0.1/32'] in json["advertisedRoutes"] (have []):
E       --- Expected value
E       +++ Current value
E       @@ -1,3 +1 @@
E       -{
E       -    "10.255.0.1/32": {}
E       -}
E       +{}
```

**Comment by eqvinox** [comment]
reworked & merged in 2691a6411adf42f4481d1b017177a80c63b717ba

**Pull request closed without merging**
